
name: Go Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go install .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        env:
          SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
          SQUARE_LOCATION_ID: ${{ secrets.SQUARE_LOCATION_ID }}
        run: go test ./test/... -v
